### ISSUE TITLE
Syntax error when running desktop utility

### ISSUE THREAD

**Issue by stevenz59** [Pharylon/KML2SQL#9]
[Scenic Landmarks.zip](https://github.com/Pharylon/KML2SQL/files/225907/Scenic.Landmarks.zip)

Receiving the following error when running kml file: 

System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near ','.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInter
nalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at KML2SQL.Uploader.Upload(SqlConnection connection, Boolean dropExistingTable)
   at KML2SQL.Uploader.Upload(String connectionString, Boolean dropExistingTable)
   at KML2SQL.MainWindow.<>c__DisplayClass11_1.<UploadFile>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
ClientConnectionId:750ae162-19b0-4cbc-9030-de077c98eae0
Error Number:102,State:1,Class:15

**Comment by Pharylon** [comment]
I just released a new version. Let me know if that fixed the issue for you.

**Comment by stevenz59** [comment]
Worked like a charm! Thank you!

**Comment by stevenz59** [comment]
On closer inspection I see a problem. A particular placemark may have multiple sets of polygon coordinates. The utility is lumping them together in the placemark column creating one polygon by  joining the individual polygons. This produces weird results. It would be better to create one row for each polygon. I don't know if this is beyond the scope of this utility but it seems to be common in the kml's that I am using.  Attached is a kml which illustrates this issue.  The very first precinct is made up of four distinct polygons. Thank you for your efforts. 
[Police Precincts.zip](https://github.com/Pharylon/KML2SQL/files/284968/Police.Precincts.zip)
